
import BarChart from '@/components/barchart'
import Bubblechart from '@/components/bubblechart'
import DoughnutChart from '@/components/donutchart'
import Linechart from '@/components/linegraph'
import PieChart from '@/components/piechart'
import PolarAreaChart from '@/components/polararea'
import RadarChart from '@/components/radarchart'
import ScatterChart from '@/components/scatterchart'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import { Scatter } from 'react-chartjs-2'
import styled from 'styled-components'


const MainCont = styled.div`

display: flex;
align-items: center;
flex-direction: column;

.m-heading{
  font-size: 45px;
  font-family: 'Roboto', sans-serif;
  margin-top:20px;
  margin-bottom: 50px;
  text-decoration: underline;
}

.heading{
  padding-left: 50px;
  width: 100vw;
  font-family: 'Roboto', sans-serif;
  font-size: 40px;
  color: gray;
  margin-bottom: 50px;
  text-decoration: underline;

}
.chart{
  height: 500px;
  width: 700px;
  display: flex;
  justify-content: center;
}
.screen{
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Chart Js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"/>
      </Head>
    
    <MainCont>
    <div className="m-heading">Data Visualization: Creating Stunning Graphs with Chart.js </div>
      <div className="screen"> 
      <div className="heading">Line Chart:</div>
      <div className="chart">
        <Linechart/>
      </div>
      </div>

      <div className="screen"> 
      <div className="heading">Bar Chart:</div>
      <div className="chart"> <BarChart/></div>
      </div>
      <div className="screen"> 
      <div className="heading">Pie Chart:</div>
      <div className="chart"> <PieChart/></div>
      </div>
      <div className="screen"> 
      <div className="heading">Bubble Chart:</div>
      <div className="chart">  <Bubblechart/></div>
      </div>
      <div className="screen"> 
      <div className="heading">Doughnut Chart:</div>
      <div className="chart"> <DoughnutChart/></div>
      </div>
      <div className="screen"> 
      <div className="heading">PolarArea Chart:</div>
      <div className="chart"><PolarAreaChart/></div>
      </div>
      <div className="screen"> 
      <div className="heading">Radar Chart:</div>
      <div className="chart"><RadarChart/></div>
      </div>
      <div className="screen"> 
      <div className="heading">Scatter Chart:</div>
      <div className="chart"><ScatterChart/></div>
      </div>      

      
     
     
    
     
      
      
      
    </MainCont>
    </>
  )
}
